shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-async]
github = "mafredri/zsh-async"

# syntax-highlighting は最後に読み込む
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
